### PR TITLE
[PAR-WDFT-248] Frederico Ratsimandresy

### PR DESCRIPTION
**Pull request by Ratsimandresy**
I pushed it but i didn't finish the last Iteration (4) yet

### CODE REVIEW

**Comment by Fanny-Sbn** [comment]
**Good commit practices**

Hello Rico ! Thanks for your lab.
 
**Iteration 1**
-
👍
with a fat arrow function and ternary
const renderGreenPeppers = () =>
document
.querySelectorAll(".green-pepper")
.forEach((oneGreenPep) =>
state.greenPeppers
? (oneGreenPep.style.visibility = "visible")
: (oneGreenPep.style.visibility = "hidden")
);

**Iteration 2**
-
👍 

**Iteration 3**
-
👍 

**Iteration 4**
-
No iteration 4

You need to do the iteration 4 to make sure you understand DOM concepts 😃

**Comment by Ratsimandresy** [comment]
Hello! Indeed, i am still stuck on iteration as i left a msg about it.
kibd of stuck :(

**Comment by Fanny-Sbn** [comment]
Hint : 

For iteration 4, basically you need to check if the state of each topping is true and if it is you have to add the price of each one to the total **and** add this ingredient in the list you can find in HTML file through DOM manipulation.

**Comment by Fanny-Sbn** [comment]
Hello Rico, thanks for iteration 4 ! 

It's working :) 

You could have also used a for in loop to iterate through the properties of an object and then check the state of each property.

Good job 💯

**Pull request closed without merging**
